[build]
  command = "npm run build"
  publish = "build/"
  functions = "functions/"

[[headers]]
  for ="/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"

[[redirects]]
  from = "/*"
  to = "/404/index.html"
  status = 404